### ISSUE TITLE
Bug: Test failures on Windows

### ISSUE THREAD

**Issue by danielbroll** [C-Otto/lnd-manageJ#80]
**Describe the bug**
Several tests fail on windows.

- de.cotto.lndmanagej.controller.ObjectMapperConfigurationIT#output_is_pretty_printed
![test](https://user-images.githubusercontent.com/98091744/210157836-9737a1f1-48ac-40c4-a011-daf1936410a1.PNG)

- de.cotto.lndmanagej.model.LiquidityBoundsWithTimestampTest#isTooOld_for_max_age_old_entry
`Expecting value to be true but was false`

- de.cotto.lndmanagej.balances.persistence.BalancesDaoImplTest.GetLocalBalanceAverage#one_old_entry
```
Expecting actual:
  Optional[CoinsAndDuration[coins=300.000, duration=PT336H]]
to contain:
  CoinsAndDuration[coins=300.000, duration=PT335H59M]
but did not.
```

**To Reproduce**
Which commands did you run to reproduce this?
`gradlew build pitest`

**Expected behavior**
All tests are green on the main branch

**Additional context**

* Which version (git commit) are you running?

lastest version main branch: f0505de0185c621cd7397817f8e24542b16d0c6a

* Which operating system and terminal software are you using?

Windows 10 Pro

**Comment by C-Otto** [comment]
Thanks. Windows is annoying :/ Timers on Windows have a very low resolution. On my Linux machine I get a very small difference, which is rounded down (so that "PT335H59M" is expected). I guess that `LocalDateTime.now` on Windows returns the same time, without any difference, which seems wrong to me. I need more coffee...

```
2023-01-01T11:40:56.522623468
2022-12-18T11:40:56.522630851
PT335H59M59.999992617S
```
